databases:
  - name: searcherApp
    databaseName: searcherapp
    user: searcherapp_user

services:
  - type: web
    name: searchertracker
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: searcherapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
